buildVariable: false
category:
- SERIF
familyName: Noto Serif Dives Akuru
recipeProvider: noto
googleFonts: true
includeSubsets:
- from: Noto Serif
  name: GF_Latin_Core
sources:
- NotoSerifDivesAkuru.glyphspackage
